import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";

export const metadata = {
  title: "Oasis Grace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body>
              <Navbar />
              {children}
              <Footer/>
          </body>
      </html>
  );
}
